"""Initial migration

Revision ID: 03d11f55c301
Revises: 
Create Date: 2026-09-27 09:55:46.401528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d11f55c301'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('center', sa.JSON(), nullable=False),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('export_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('date_range', sa.JSON(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_export_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    op.create_index(op.f('ix_export_jobs_export_id'), 'export_jobs', ['export_id'], unique=True)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_table('waste_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('sector_id', sa.String(length=50), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('estimated_tonnage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('threat_level', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='threatlevel'), nullable=False),
    sa.Column('waste_type', sa.Enum('MIXED', 'CONSTRUCTION', 'HAZARDOUS', 'ELECTRONIC', 'PLASTIC', 'ORGANIC', 'MEDICAL', 'OTHER', name='wastetype'), nullable=True),
    sa.Column('detection_date', sa.DateTime(), nullable=False),
    sa.Column('sensor', sa.String(length=100), nullable=True),
    sa.Column('ndvi_before', sa.Float(), nullable=True),
    sa.Column('ndvi_after', sa.Float(), nullable=True),
    sa.Column('delta_ndvi', sa.Float(), nullable=True),
    sa.Column('swir_mean', sa.Float(), nullable=True),
    sa.Column('distance_to_water_km', sa.Float(), nullable=True),
    sa.Column('distance_to_protected_km', sa.Float(), nullable=True),
    sa.Column('scene_t0', sa.String(length=100), nullable=True),
    sa.Column('scene_t1', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_waste_sites_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_sites'))
    )
    op.create_index('ix_waste_sites_detection_date', 'waste_sites', ['detection_date'], unique=False)
    op.create_index('ix_waste_sites_sector_active', 'waste_sites', ['sector_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_waste_sites_site_id'), 'waste_sites', ['site_id'], unique=True)
    op.create_index('ix_waste_sites_threat_level', 'waste_sites', ['threat_level'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('waste_site_id', sa.UUID(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_alerts_assignee_id_users')),
    sa.ForeignKeyConstraint(['waste_site_id'], ['waste_sites.id'], name=op.f('fk_alerts_waste_site_id_waste_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_table('citizen_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('waste_site_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('threat_level', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='threatlevel'), nullable=False),
    sa.Column('waste_type', sa.Enum('MIXED', 'CONSTRUCTION', 'HAZARDOUS', 'ELECTRONIC', 'PLASTIC', 'ORGANIC', 'MEDICAL', 'OTHER', name='wastetype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'RESOLVED', name='reportstatus'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_citizen_reports_assignee_id_users')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_citizen_reports_reporter_id_users')),
    sa.ForeignKeyConstraint(['waste_site_id'], ['waste_sites.id'], name=op.f('fk_citizen_reports_waste_site_id_waste_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen_reports'))
    )
    op.create_index(op.f('ix_citizen_reports_created_at'), 'citizen_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_citizen_reports_report_id'), 'citizen_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_citizen_reports_status'), 'citizen_reports', ['status'], unique=False)
    op.create_index('ix_reports_location', 'citizen_reports', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_reports_status_created', 'citizen_reports', ['status', 'created_at'], unique=False)
    op.create_table('waste_site_time_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waste_site_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['waste_site_id'], ['waste_sites.id'], name=op.f('fk_waste_site_time_series_waste_site_id_waste_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waste_site_time_series')),
    sa.UniqueConstraint('waste_site_id', 'date', name='uq_site_date')
    )
    op.create_index('ix_timeseries_site_date', 'waste_site_time_series', ['waste_site_id', 'date'], unique=False)
    op.create_index(op.f('ix_waste_site_time_series_date'), 'waste_site_time_series', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_site_time_series_date'), table_name='waste_site_time_series')
    op.drop_index('ix_timeseries_site_date', table_name='waste_site_time_series')
    op.drop_table('waste_site_time_series')
    op.drop_index('ix_reports_status_created', table_name='citizen_reports')
    op.drop_index('ix_reports_location', table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_status'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_report_id'), table_name='citizen_reports')
    op.drop_index(op.f('ix_citizen_reports_created_at'), table_name='citizen_reports')
    op.drop_table('citizen_reports')
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_waste_sites_threat_level', table_name='waste_sites')
    op.drop_index(op.f('ix_waste_sites_site_id'), table_name='waste_sites')
    op.drop_index('ix_waste_sites_sector_active', table_name='waste_sites')
    op.drop_index('ix_waste_sites_detection_date', table_name='waste_sites')
    op.drop_table('waste_sites')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_export_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sectors')
    # ### end Alembic commands ###